# Python and Numpy

## Libraries and namespaces

Core Python can do relatively little. Fortunately though, there are many Python libraries that can add to its functionality. For now the one we'll be focusing on is __NumPy__, which contains definitions for a lot of commonly used mathematical functions and constants. NumPy can be imported like this:

In [1]:
import numpy

and the variables it contains can be referenced like this:

In [2]:
print(numpy.cos(0))

1.0


Notice the __numpy.__ in the above example. Without this, NumPy's variables are not accessible:

In [3]:
print(cos(0))

NameError: name 'cos' is not defined

This is because Python groups variables into _namespaces_. The NumPy library has its own namespace which contains all the variables it defines. This namespace is separate from the namespace you're currently working in, which contains a single user-defined variable, `numpy` (and also some built-in variables).

As well as importing an entire library, you can import individual variables into the current namespace. Then you can reference these variables without going through `numpy`.

In [5]:
from numpy import cos, sin
print(sin(0), cos(0))

0.0 1.0


The `import` statement also lets you rename a library when you import it. You'll usually see numpy imported and used like this, and this is how we'll be using it throughout this course:

In [6]:
import numpy as np
print(np.cos(0))

1.0


## Arrays

Core Python has no concept of arrays as such, but NumPy does. First though, it's useful to look at _lists_, which are the closest basic Python equivalent to an array. Lists are defined like this:

In [7]:
mylist = [1, 2, 5]
print(mylist)

[1, 2, 5]


Lists (and arrays, and all other types of sequence) are indexed using square brackets, and indices start at 0.

In [8]:
# Print the first and third items in the list
print(mylist[0], mylist[2])

# Print an item that doesn't exist
print(mylist[6])

1 5


IndexError: list index out of range

You can convert a list into a NumPy array using the `array()` function in NumPy:

In [9]:
myarr = np.array(mylist)
print(myarr)

[1 2 5]


There are also NumPy functions for quickly generating larger arrays. The `arange()` function makes an array containing a sequence of numbers and can be used in several ways:
- if given a single value, the sequence starts at 0, stops at the given value and goes in steps of 1
- if given two values, the sequence goes from the first to the second in steps of 1
- if given three values, the sequence goes from the first to the second in steps of the third

In [21]:
# Make an array of numbers between 0 and 10
print(np.arange(10.0))

# Make an array of numbers between 3 and 10
print(np.arange(3.0, 10.0))

# Make an array of numbers between 3 and 10 in steps of 0.4
print(np.arange(3.0, 10.0, 0.8))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 3.  4.  5.  6.  7.  8.  9.]
[ 3.   3.8  4.6  5.4  6.2  7.   7.8  8.6  9.4]


Notice that the values in the sequence are not inclusive of the given end value.

Alternatively, you can make an empty array using the `zeros()` function, which takes a single argument corresponding to the shape of the array.

In [28]:
# Make a 7-elements long array of nothing
print(np.zeros(7))

# Make a 2D array of nothing
print(np.zeros((7, 3)))

[ 0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


Notice the extra brackets in the second command, since we are grouping together the values as a single argument to the function.

### Working with arrays

### Methods and attributes

Some Python variables, including NumPy arrays, have their own namespaces which contain functions and variables that relate to that variable. In this context these are called _methods_ and _attributes_, respectively. For instance, NumPy arrays have `min()`, `mean()` and `max()` methods, which do pretty much what you'd expect:

In [10]:
print(myarr.min(), myarr.mean(), myarr.max())

1 2.66666666667 5


NumPy attributes include the `shape` and `size` values:

In [11]:
print(myarr.shape, myarr.size)

(3,) 3


## Slicing (quick)

## Functions on arrays

## Super fast units