# Python and Numpy

## Useful Links

1. [NumPy Quickstart Guide](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
1. [NumPy Documentation](http://docs.scipy.org/doc/numpy/)
1. [Astropy Units Documentation](http://docs.astropy.org/en/stable/units/index.html)
1. [Introduction to Units in SunPy](http://docs.sunpy.org/en/stable/guide/tour.html#quantities-and-units)
1. [Scipy Lecture Notes](http://www.scipy-lectures.org/)

## Libraries and namespaces

Core Python can do relatively little. Fortunately though, there are many Python libraries that can add to its functionality. For now the one we'll be focusing on is __NumPy__, which contains definitions for a lot of commonly used mathematical functions and constants. NumPy can be imported like this:

In [1]:
import numpy

and the variables it contains can be referenced like this:

In [2]:
print(numpy.cos(0))

1.0


Notice the __numpy.__ in the above example. Without this, NumPy's variables are not accessible:

In [3]:
print(cos(0))

NameError: name 'cos' is not defined

This is because Python groups variables into _namespaces_. The NumPy library has its own namespace which contains all the variables it defines. This namespace is separate from the namespace you're currently working in, which contains a single user-defined variable, `numpy` (and also some built-in variables).

As well as importing an entire library, you can import individual variables into the current namespace. Then you can reference these variables without going through `numpy`.

In [4]:
from numpy import cos, sin
print(sin(0), cos(0))

0.0 1.0


The `import` statement also lets you rename a library when you import it. You'll usually see numpy imported and used like this, and this is how we'll be using it throughout this course:

In [5]:
import numpy as np
print(np.cos(0))

1.0


## Arrays

Core Python has no concept of arrays as such, but NumPy does. First though, it's useful to look at _lists_, which are the closest basic Python equivalent to an array. Lists are defined like this:

In [6]:
mylist = [1, 2, 5]
print(mylist)

[1, 2, 5]


Lists (and arrays, and all other types of sequence) are indexed using square brackets, and indices start at 0.

In [7]:
# Print the first and third items in the list
print(mylist[0], mylist[2])

# Print an item that doesn't exist
print(mylist[6])

1 5


IndexError: list index out of range

You can convert a list into a NumPy array using the `array()` function in NumPy:

In [8]:
myarr = np.array(mylist)
print(myarr)

[1 2 5]


There are also NumPy functions for quickly generating larger arrays. The `arange()` function makes an array containing a sequence of numbers and can be used in several ways:
- if given a single value, the sequence starts at 0, stops at the given value and goes in steps of 1
- if given two values, the sequence goes from the first to the second in steps of 1
- if given three values, the sequence goes from the first to the second in steps of the third

In [9]:
# Make an array of numbers between 0 and 10
print(np.arange(10.0))

# Make an array of numbers between 3 and 10
print(np.arange(3.0, 10.0))

# Make an array of numbers between 3 and 10 in steps of 0.4
print(np.arange(3.0, 10.0, 0.8))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[3. 4. 5. 6. 7. 8. 9.]
[3.  3.8 4.6 5.4 6.2 7.  7.8 8.6 9.4]


Notice that the values in the sequence are not inclusive of the given end value.

Alternatively, you can make an empty array using the `zeros()` function, which takes a single argument corresponding to the shape of the array.

In [10]:
# Make a 7-elements long array of nothing
print(np.zeros(7))

# Make a 2D array of nothing
print(np.zeros((7, 3)))

[0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Notice the extra brackets in the second command, since we are grouping together the values as a single argument to the function.

### Functions on arrays

Many functions can be performed on every element in an array at once. These functions take the array as input and return an array of the same size. The `sin()` and `cos()` functions are good examples of this.

Note: `sin()` and `cos()` take their input in radians.

In [11]:
myarr = np.arange(0, 180, 10) * (np.pi / 180)
print(np.sin(myarr))

[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.         0.98480775 0.93969262
 0.8660254  0.76604444 0.64278761 0.5        0.34202014 0.17364818]


There are also plenty of functions that calculate and return single values from an array input. For instance, the `np.min()`, `np.mean()` and `np.max()` functions do pretty much what you would expect:

In [12]:
print(np.min(myarr), np.mean(myarr), np.max(myarr))

0.0 1.48352986419518 2.9670597283903604


## Methods and attributes

Some Python variables, including NumPy arrays, have their own namespaces which contain functions and variables that relate to that variable. In this context these are called _methods_ and attributes, respectively. These are accessed in the same way as variables in libraries, with the syntax `variable.method()` or `variable.attribute`.

Many of the methods associated with NumPy arrays reproduce the functionality of external functions, such as the `array.min()`, `array.mean()` and `array.max()` methods, which are equivalent to the functions used above:

In [13]:
print(myarr.min(), myarr.mean(), myarr.max())

0.0 1.48352986419518 2.9670597283903604


Attributes usually contain useful information about the variable. For instance, the shape and size of a NumPy array are stored in the `array.shape` and `array.size` attributes.

In [14]:
myarr = np.zeros((6, 4))
print(myarr.shape, myarr.size)

(6, 4) 24


## Slicing (quick)

You can reference part of an array (_slice_ it) with a slightly expanded version of the syntax used to access individual elements.

In [15]:
myarr = np.arange(50)

# Access just the 15th element of the array.
print(myarr[14])

# Access ten elements starting at the 15th
print(myarr[14:24])

14
[14 15 16 17 18 19 20 21 22 23]


Just like with the `arange()` function, note that the end index is not included. Also similarly to `arange()`, we can also include a `step` value to get only certain indices in the specified range:

In [16]:
# Get every other element in the range used above.
print(myarr[14:24:2])

# You can also go backwards
print(myarr[24:14:-2])

[14 16 18 20 22]
[24 22 20 18 16]


## Astropy units - a super brief overview

Another very useful Python package for solar physics is AstroPy. This provides lots very powerful features, but the one we will focus on now is the units package. This allows you to attach physical units to a value, and for Python to then sensibly interpret that value.

In [17]:
import astropy.units as u

x = 1 * u.m
y = 1 * u.imperial.foot
print(x + y)

x = np.arange(0, 180, 10) * u.deg
print(np.sin(x))

1.3048 m
[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.         0.98480775 0.93969262
 0.8660254  0.76604444 0.64278761 0.5        0.34202014 0.17364818]
